# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Trinanjan123.github.io/nbdev_practice/"

git_url = "https://github.com/Trinanjan123/nbdev_practice/tree/{branch}/"

def custom_doc_links(name): return None
